sudo: false
addons:
  sonarcloud:
    #organization: "mvp-org"
      token: ${SONAR_TOKEN}

jdk:
  - openjdk8
language: java
script:
  - mvn clean install
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=mv-prog-github -Dsonar.projectKey=mavenExampleIC
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mv-prog-github