sudo: false
addons:
  sonarcloud:
    organization: "mvp-org"
    token:
      secure: "4c3d019e5ce2111f2c551010869a71c881e86f21"

jdk:
  - openjdk8
language: java
script:
  - mvn test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mv-prog_mavenExampleIC